//! token-boundary contract of the prefix-anchored rules.
//!
//! a prefix token matches only where a token starts: at the start of the text, after a byte that
//! is not an ascii word byte, or right after a source-code string escape sequence (`\n`, `\r`,
//! `\t`, `\f`, `\b`, `\v`, an octal escape such as `\0` or `\012`, `\xHH`, `\uHHHH`, `\UHHHHHHHH`
//! or `\u{H..HHHHHH}`, and any other `\<letter>` escape), since json- and c-escaped text glues the
//! token to the escape's last byte. the end is left open: a token glued to trailing word bytes is
//! still reported, because recall wins for tier 1. the negative cases plant each token inside a
//! generated base64 run, the shape that made `facebook-access-token` fire on pem bodies; the
//! positive cases put the same token into the contexts real tokens are written in. every opaque
//! value is generated at runtime, and so is the pem armor.

use regex::bytes::Regex;
use sekretbarilo::config::allowlist::CompiledAllowlist;
use sekretbarilo::config::{ProjectConfig, build_allowlist};
use sekretbarilo::diff::parser::{AddedLine, DiffFile};
use sekretbarilo::scanner::engine::{redact_text, scan, scan_text};
use sekretbarilo::scanner::rules::{CompiledScanner, Rule, compile_rules, load_default_rules};
use std::ops::Range;
use std::sync::LazyLock;

static RULES: LazyLock<Vec<Rule>> =
    LazyLock::new(|| load_default_rules().expect("default rules load"));

static SCANNER: LazyLock<CompiledScanner> =
    LazyLock::new(|| compile_rules(&RULES).expect("default rules compile"));

static ALLOWLIST: LazyLock<CompiledAllowlist> = LazyLock::new(|| {
    build_allowlist(&ProjectConfig::default(), &RULES).expect("default allowlist")
});

/// an ordinary data path: exempt from nothing.
const FILE_PATH: &str = "deploy/settings.conf";

/// the start boundaries as written in rules.toml: `\b` where the token starts with a literal word
/// byte, the half boundary where it starts with a class. each also admits any source-code escape
/// sequence (`\n`, `\r`, `\t`, `\f`, `\b`, `\v`, octal, `\xHH`, `\uHHHH`, `\UHHHHHHHH`, `\u{...}`,
/// or a bare `\<letter>`), tried longest-form-first so a multi-byte escape is consumed whole.
const WORD_START: &str = r"(?:%[0-9A-Fa-f]{2}|\[[0-9;:]*[mK]|\\(?:u\{[0-9A-Fa-f]{1,6}\}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8}|x[0-9A-Fa-f]{2}|[0-7]{1,3}|[A-Za-z])|(?-u:\b))";
const CLASS_START: &str = r"(?:%[0-9A-Fa-f]{2}|\[[0-9;:]*[mK]|\\(?:u\{[0-9A-Fa-f]{1,6}\}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8}|x[0-9A-Fa-f]{2}|[0-7]{1,3}|[A-Za-z])|(?-u:\b{start-half}))";

const B64: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
const ALNUM: &[u8] = b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
const ALNUM_US: &[u8] = b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_";
const ALNUM_DASH: &[u8] = b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-";
const URLSAFE: &[u8] = b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_-";
const UPPER_DIGIT: &[u8] = b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const LOWER_DIGIT: &[u8] = b"0123456789abcdefghijklmnopqrstuvwxyz";
/// bech32 without `1`, `b`, `i` and `o`, upper-case as age writes its secret keys.
const BECH32_UPPER: &[u8] = b"023456789ACDEFGHJKLMNPQRSTUVWXYZ";
const HEX: &[u8] = b"0123456789abcdef";
const HEX_MIXED: &[u8] = b"0123456789abcdefABCDEF";
const DIGIT: &[u8] = b"0123456789";

enum Part {
    Lit(&'static str),
    /// generated bytes from an alphabet; a bounded rule's last run is generated at its maximum
    /// length, so one more byte of the alphabet makes the token too long.
    Run(&'static [u8], usize),
}

use Part::{Lit, Run};

struct Shape {
    rule: &'static str,
    /// context a key-anchored rule needs on the same line.
    lead: &'static str,
    parts: &'static [Part],
}

const fn shape(rule: &'static str, parts: &'static [Part]) -> Shape {
    Shape {
        rule,
        lead: "",
        parts,
    }
}

const SHAPES: &[Shape] = &[
    shape("aws-access-key-id", &[Lit("AKIA"), Run(UPPER_DIGIT, 16)]),
    shape(
        "github-personal-access-token",
        &[Lit("ghp_"), Run(ALNUM, 36)],
    ),
    shape("github-oauth-token", &[Lit("gho_"), Run(ALNUM, 36)]),
    shape("github-app-token", &[Lit("ghs_"), Run(ALNUM, 36)]),
    shape("github-refresh-token", &[Lit("ghr_"), Run(ALNUM, 36)]),
    shape(
        "github-fine-grained-pat",
        &[Lit("github_pat_"), Run(ALNUM_US, 82)],
    ),
    shape(
        "gitlab-personal-access-token",
        &[Lit("glpat-"), Run(URLSAFE, 20)],
    ),
    shape("slack-bot-token", &[Lit("xoxb-"), Run(ALNUM_DASH, 48)]),
    shape("slack-user-token", &[Lit("xoxp-"), Run(ALNUM_DASH, 48)]),
    shape("slack-app-token", &[Lit("xapp-"), Run(ALNUM_DASH, 48)]),
    shape("stripe-secret-key-live", &[Lit("sk_live_"), Run(ALNUM, 24)]),
    shape("stripe-secret-key-test", &[Lit("sk_test_"), Run(ALNUM, 24)]),
    shape(
        "stripe-publishable-key-live",
        &[Lit("pk_live_"), Run(ALNUM, 24)],
    ),
    shape(
        "sendgrid-api-key",
        &[Lit("SG."), Run(URLSAFE, 22), Lit("."), Run(URLSAFE, 43)],
    ),
    shape(
        "jwt-token",
        &[
            Lit("eyJ"),
            Run(URLSAFE, 20),
            Lit(".eyJ"),
            Run(URLSAFE, 30),
            Lit("."),
            Run(URLSAFE, 43),
        ],
    ),
    shape(
        "digitalocean-personal-access-token",
        &[Lit("dop_v1_"), Run(HEX, 64)],
    ),
    shape("digitalocean-oauth-token", &[Lit("doo_v1_"), Run(HEX, 64)]),
    shape(
        "digitalocean-refresh-token",
        &[Lit("dor_v1_"), Run(HEX, 64)],
    ),
    shape("npm-access-token", &[Lit("npm_"), Run(ALNUM, 36)]),
    shape("pypi-api-token", &[Lit("pypi-"), Run(URLSAFE, 50)]),
    shape("docker-hub-pat", &[Lit("dckr_pat_"), Run(URLSAFE, 27)]),
    shape("new-relic-api-key", &[Lit("NRAK-"), Run(UPPER_DIGIT, 27)]),
    shape(
        "terraform-cloud-token",
        &[Run(ALNUM, 14), Lit(".atlasv1."), Run(URLSAFE, 67)],
    ),
    shape("anthropic-api-key", &[Lit("sk-ant-"), Run(URLSAFE, 60)]),
    shape(
        "openai-api-key-legacy",
        &[Lit("sk-"), Run(ALNUM, 20), Lit("T3BlbkFJ"), Run(ALNUM, 20)],
    ),
    shape("openai-api-key", &[Lit("sk-proj-"), Run(URLSAFE, 156)]),
    shape("gcp-api-key", &[Lit("AIza"), Run(URLSAFE, 35)]),
    shape(
        "gcp-oauth-client-secret",
        &[Lit("GOCSPX-"), Run(URLSAFE, 28)],
    ),
    shape("alibaba-access-key-id", &[Lit("LTAI"), Run(ALNUM, 20)]),
    shape(
        "gitlab-pipeline-trigger-token",
        &[Lit("glptt-"), Run(URLSAFE, 40)],
    ),
    shape(
        "gitlab-runner-registration-token",
        &[Lit("glrt-"), Run(URLSAFE, 20)],
    ),
    shape("gitlab-ci-job-token", &[Lit("glcbt-"), Run(URLSAFE, 30)]),
    shape("huggingface-access-token", &[Lit("hf_"), Run(ALNUM, 34)]),
    shape("replicate-api-token", &[Lit("r8_"), Run(ALNUM, 38)]),
    shape(
        "stripe-restricted-key-live",
        &[Lit("rk_live_"), Run(ALNUM, 24)],
    ),
    shape(
        "stripe-restricted-key-test",
        &[Lit("rk_test_"), Run(ALNUM, 24)],
    ),
    shape("square-access-token", &[Lit("sq0atp-"), Run(URLSAFE, 22)]),
    shape("square-oauth-secret", &[Lit("sq0csp-"), Run(URLSAFE, 43)]),
    shape(
        "planetscale-password",
        &[Lit("pscale_pw_"), Run(URLSAFE, 43)],
    ),
    shape(
        "planetscale-api-token",
        &[Lit("pscale_tkn_"), Run(URLSAFE, 43)],
    ),
    shape("mailgun-private-api-token", &[Lit("key-"), Run(HEX, 32)]),
    shape(
        "mailchimp-api-key",
        &[Run(HEX, 32), Lit("-us"), Run(DIGIT, 2)],
    ),
    shape(
        "sendinblue-api-key",
        &[Lit("xkeysib-"), Run(HEX, 64), Lit("-"), Run(ALNUM, 16)],
    ),
    shape("buildkite-api-token", &[Lit("bkua_"), Run(HEX, 40)]),
    shape("grafana-cloud-api-token", &[Lit("glc_"), Run(ALNUM, 40)]),
    shape(
        "grafana-service-account-token",
        &[Lit("glsa_"), Run(ALNUM_US, 41)],
    ),
    shape("sentry-auth-token", &[Lit("sntrys_"), Run(URLSAFE, 60)]),
    shape(
        "dynatrace-api-token",
        &[
            Lit("dt0c01."),
            Run(UPPER_DIGIT, 24),
            Lit("."),
            Run(UPPER_DIGIT, 64),
        ],
    ),
    shape("rubygems-api-key", &[Lit("rubygems_"), Run(HEX, 48)]),
    shape("nuget-api-key", &[Lit("oy2"), Run(LOWER_DIGIT, 43)]),
    shape(
        "age-secret-key",
        &[Lit("AGE-SECRET-KEY-1"), Run(BECH32_UPPER, 58)],
    ),
    shape("fly-io-api-token", &[Lit("fo1_"), Run(URLSAFE, 43)]),
    shape("pulumi-access-token", &[Lit("pul-"), Run(HEX, 40)]),
    shape("linear-api-key", &[Lit("lin_api_"), Run(ALNUM, 40)]),
    shape(
        "shopify-access-token-admin",
        &[Lit("shpat_"), Run(HEX_MIXED, 32)],
    ),
    shape(
        "shopify-access-token-custom-app",
        &[Lit("shpca_"), Run(HEX_MIXED, 32)],
    ),
    shape(
        "shopify-access-token-private-app",
        &[Lit("shppa_"), Run(HEX_MIXED, 32)],
    ),
    shape("facebook-access-token", &[Lit("EAA"), Run(ALNUM, 40)]),
    shape(
        "hashicorp-vault-service-token",
        &[Lit("hvs."), Run(URLSAFE, 90)],
    ),
    shape(
        "hashicorp-vault-batch-token",
        &[Lit("hvb."), Run(URLSAFE, 90)],
    ),
    shape(
        "sourcegraph-access-token",
        &[Lit("sgp_"), Run(HEX_MIXED, 40)],
    ),
    shape(
        "figma-personal-access-token",
        &[Lit("figd_"), Run(URLSAFE, 40)],
    ),
    shape(
        "mapbox-api-token",
        &[Lit("pk."), Run(URLSAFE, 60), Lit("."), Run(URLSAFE, 22)],
    ),
    shape("dropbox-api-token", &[Lit("sl."), Run(URLSAFE, 120)]),
    shape(
        "launchdarkly-sdk-key",
        &[
            Lit("sdk-"),
            Run(HEX, 8),
            Lit("-"),
            Run(HEX, 4),
            Lit("-"),
            Run(HEX, 4),
            Lit("-"),
            Run(HEX, 4),
            Lit("-"),
            Run(HEX, 12),
        ],
    ),
    shape("notion-api-token", &[Lit("ntn_"), Run(ALNUM, 46)]),
    shape("databricks-api-token", &[Lit("dapi"), Run(HEX, 32)]),
    Shape {
        rule: "twilio-api-key",
        lead: "twilio ",
        parts: &[Lit("SK"), Run(HEX_MIXED, 32)],
    },
];

/// contexts a real token is written in; `{}` is where the token goes.
const CONTEXTS: &[&str] = &[
    "{}",
    "TOKEN={}",
    "token: {}",
    "token = \"{}\"",
    "token = '{}'",
    "  \t{}",
    "Authorization: Bearer {}",
    "client.login({})",
    "tokens = [first,{},last]",
    "https://api.service.test/v1/items?token={}&page=2",
];

/// xorshift64*, seeded per rule so every shape gets its own bytes on every machine and run.
struct Generator(u64);

impl Generator {
    fn for_rule(rule: &str, salt: u64) -> Self {
        // fnv-1a over the rule id
        let seed = rule.bytes().fold(0xcbf2_9ce4_8422_2325_u64, |hash, byte| {
            (hash ^ u64::from(byte)).wrapping_mul(0x0100_0000_01b3)
        });
        Self((seed ^ salt) | 1)
    }

    fn next(&mut self) -> u64 {
        self.0 ^= self.0 >> 12;
        self.0 ^= self.0 << 25;
        self.0 ^= self.0 >> 27;
        self.0 = self.0.wrapping_mul(0x2545_F491_4F6C_DD1D);
        self.0
    }

    fn pick(&mut self, alphabet: &[u8]) -> char {
        char::from(alphabet[(self.next() >> 32) as usize % alphabet.len()])
    }

    fn run(&mut self, alphabet: &[u8], length: usize) -> String {
        (0..length).map(|_| self.pick(alphabet)).collect()
    }

    fn bytes(&mut self, length: usize) -> Vec<u8> {
        (0..length).map(|_| (self.next() >> 56) as u8).collect()
    }
}

impl Shape {
    fn token(&self) -> String {
        let mut generator = Generator::for_rule(self.rule, 0);
        self.parts
            .iter()
            .map(|part| match part {
                Lit(text) => (*text).to_owned(),
                Run(alphabet, length) => generator.run(alphabet, *length),
            })
            .collect()
    }

    /// a word byte of the last run's alphabet: appended to the token it lengthens the run.
    fn continuation(&self) -> char {
        self.parts
            .iter()
            .rev()
            .find_map(|part| match part {
                Run(alphabet, _) => alphabet
                    .iter()
                    .copied()
                    .find(u8::is_ascii_alphanumeric)
                    .map(char::from),
                Lit(_) => None,
            })
            .expect("a shape ends in a generated run")
    }

    fn pattern(&self) -> &'static str {
        &RULES
            .iter()
            .find(|rule| rule.id == self.rule)
            .unwrap_or_else(|| panic!("{} is a default rule", self.rule))
            .regex_pattern
    }

    /// the rule as it was before the boundary: whatever it matches here is what the boundary
    /// removes, so a negative case it does not match would pass for the wrong reason.
    fn unbounded(&self) -> Regex {
        Regex::new(
            &self
                .pattern()
                .replace(WORD_START, "")
                .replace(CLASS_START, ""),
        )
        .expect("the unbounded pattern compiles")
    }
}

fn diff_file(lines: &[&str]) -> DiffFile {
    DiffFile {
        path: FILE_PATH.to_owned(),
        is_new: false,
        is_deleted: false,
        is_renamed: false,
        is_binary: false,
        context: None,
        added_lines: lines
            .iter()
            .enumerate()
            .map(|(index, line)| AddedLine {
                line_number: index + 1,
                content: line.as_bytes().to_vec(),
            })
            .collect(),
    }
}

/// rule ids reported on either surface; values stay out of failure messages.
fn reported_rules(text: &str) -> Vec<String> {
    let lines: Vec<&str> = text.lines().collect();
    let mut rules: Vec<String> = scan(&[diff_file(&lines)], &SCANNER, &ALLOWLIST)
        .into_iter()
        .map(|finding| finding.rule_id)
        .chain(
            scan_text(text, &SCANNER, &ALLOWLIST)
                .into_iter()
                .map(|matched| matched.rule_id),
        )
        .collect();
    rules.sort();
    rules.dedup();
    rules
}

fn armor(edge: &str) -> String {
    let dashes = "-".repeat(5);
    format!("{dashes}{edge} PRIVATE KEY{dashes}")
}

fn base64(bytes: &[u8]) -> String {
    let mut encoded = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let word = chunk
            .iter()
            .enumerate()
            .fold(0_u32, |word, (index, &byte)| {
                word | (u32::from(byte) << (16 - 8 * index))
            });
        for index in 0..4 {
            if index <= chunk.len() {
                encoded.push(char::from(B64[((word >> (18 - 6 * index)) & 63) as usize]));
            } else {
                encoded.push('=');
            }
        }
    }
    encoded
}

fn pem_block(body: &[String]) -> String {
    let mut lines = vec![armor("BEGIN")];
    lines.extend(body.iter().cloned());
    lines.push(armor("END"));
    lines.join("\n")
}

/// `token` inside a base64 run: `before` random bytes, then the token, then `after` random bytes.
/// the bytes touching the token are forced alphanumeric, since `+` and `/` are boundaries.
fn planted(generator: &mut Generator, token: &str, before: usize, after: usize) -> String {
    let mut left = generator.run(B64, before);
    left.pop();
    left.push(generator.pick(ALNUM));
    let mut right = generator.pick(ALNUM).to_string();
    right.push_str(&generator.run(B64, after.saturating_sub(1)));
    format!("{left}{token}{right}")
}

#[test]
fn every_boundary_rule_has_a_shape() {
    let guarded: Vec<&str> = RULES
        .iter()
        .filter(|rule| {
            rule.regex_pattern.contains(WORD_START) || rule.regex_pattern.contains(CLASS_START)
        })
        .map(|rule| rule.id.as_str())
        .collect();
    let shaped: Vec<&str> = SHAPES.iter().map(|shape| shape.rule).collect();
    let missing: Vec<&&str> = guarded.iter().filter(|id| !shaped.contains(id)).collect();
    let unguarded: Vec<&&str> = shaped.iter().filter(|id| !guarded.contains(id)).collect();
    assert!(missing.is_empty(), "rules without a shape: {missing:?}");
    assert!(
        unguarded.is_empty(),
        "shapes whose rule has no start boundary: {unguarded:?}"
    );
}

#[test]
fn prefix_inside_a_wrapped_pem_body_is_not_reported() {
    let mut failures = Vec::new();
    for shape in SHAPES {
        let token = shape.token();
        let unbounded = shape.unbounded();
        for column in [1, 7, 21] {
            let mut generator = Generator::for_rule(shape.rule, column as u64);
            let tail = 64_usize.saturating_sub(column + token.len()).max(8);
            let line = format!(
                "{}{}",
                shape.lead,
                planted(&mut generator, &token, column, tail)
            );
            assert!(
                unbounded.is_match(line.as_bytes()),
                "{} at column {column}: the unbounded rule does not match the planted line",
                shape.rule
            );
            let body = vec![
                generator.run(B64, 64),
                line,
                generator.run(B64, 64),
                generator.run(B64, 42) + "==",
            ];
            let rules = reported_rules(&pem_block(&body));
            if rules.iter().any(|rule| rule == shape.rule) {
                failures.push(format!("{} at column {column}", shape.rule));
            }
        }
    }
    assert!(
        failures.is_empty(),
        "prefix matched mid-run:\n{}",
        failures.join("\n")
    );
}

#[test]
fn prefix_inside_an_unwrapped_base64_line_is_not_reported() {
    let mut failures = Vec::new();
    for shape in SHAPES {
        let token = shape.token();
        let mut generator = Generator::for_rule(shape.rule, 0x0b64);
        let line = format!(
            "{}{}",
            shape.lead,
            planted(&mut generator, &token, 300, 300)
        );
        assert!(
            shape.unbounded().is_match(line.as_bytes()),
            "{}: the unbounded rule does not match the planted line",
            shape.rule
        );
        if reported_rules(&line).iter().any(|rule| rule == shape.rule) {
            failures.push(shape.rule);
        }
    }
    assert!(failures.is_empty(), "prefix matched mid-run: {failures:?}");
}

#[test]
fn word_byte_before_the_prefix_blocks_the_match() {
    // the right side is a delimiter, so only the start boundary can reject these.
    let mut failures = Vec::new();
    for shape in SHAPES {
        let token = shape.token();
        let mut generator = Generator::for_rule(shape.rule, 0x1eff);
        for glue in [generator.pick(ALNUM), '_'] {
            let line = format!("{}value={glue}{token} end", shape.lead);
            assert!(
                shape.unbounded().is_match(line.as_bytes()),
                "{}: the unbounded rule does not match",
                shape.rule
            );
            if reported_rules(&line).iter().any(|rule| rule == shape.rule) {
                failures.push(format!("{} after {glue:?}", shape.rule));
            }
        }
    }
    assert!(
        failures.is_empty(),
        "prefix matched after a word byte:\n{}",
        failures.join("\n")
    );
}

#[test]
fn token_glued_to_trailing_word_bytes_is_still_reported() {
    // the end is left open on purpose: a real-length token that runs on into word bytes is
    // reported from its first byte, whole or as its real-length head, never dropped.
    let mut failures = Vec::new();
    for shape in SHAPES {
        let token = shape.token();
        let line = format!("{}value={token}{} end", shape.lead, shape.continuation());
        let start = shape.lead.len() + "value=".len();
        let on_diff = scan(&[diff_file(&[line.as_str()])], &SCANNER, &ALLOWLIST)
            .iter()
            .any(|finding| {
                finding.rule_id == shape.rule && finding.matched_value.starts_with(token.as_bytes())
            });
        let on_text = scan_text(&line, &SCANNER, &ALLOWLIST)
            .iter()
            .any(|matched| {
                matched.rule_id == shape.rule
                    && matched.range.start == start
                    && matched.range.end >= start + token.len()
            });
        if !on_diff || !on_text {
            failures.push(format!("{}: diff={on_diff} text={on_text}", shape.rule));
        }
    }
    assert!(
        failures.is_empty(),
        "glued token not reported:\n{}",
        failures.join("\n")
    );
}

/// json and c string contexts; `<esc>` is the escape before the token, `<token>` the token.
const ESCAPED_CONTEXTS: &[&str] = &[
    r#"{"level":"info","msg":"session opened<esc><token>\nnext"}"#,
    r#"fprintf(log, "credential:<esc><token>\n");"#,
];

/// every escape shape the start boundary must admit: the three whitespace letters, three more
/// single-letter c escapes, an octal escape of one and of three digits, a two-hex-digit `\x`
/// escape, a 4-hex `\u`, an 8-hex `\U`, and the brace form `\u{...}`.
const STRING_ESCAPES: &[&str] = &[
    r"\n",
    r"\r",
    r"\t",
    r"\f",
    r"\b",
    r"\v",
    r"\0",
    r"\012",
    r"\x20",
    r"\u000a",
    r"\U0000000a",
    r"\u{a}",
];

#[test]
fn token_after_a_string_escape_is_reported() {
    // an escape's last byte is a word byte, so without the escape alternative the start boundary
    // would reject every token that opens an escaped line.
    let mut failures = Vec::new();
    for shape in SHAPES {
        let token = shape.token();
        for escape in STRING_ESCAPES.iter().copied() {
            for context in ESCAPED_CONTEXTS {
                let (before, after) = context
                    .split_once("<token>")
                    .expect("a context carries a token placeholder");
                let before = format!("{}{}", shape.lead, before.replace("<esc>", escape));
                let line = format!("{before}{token}{after}");
                let span: Range<usize> = before.len()..before.len() + token.len();
                let on_diff = scan(&[diff_file(&[line.as_str()])], &SCANNER, &ALLOWLIST)
                    .iter()
                    .any(|finding| {
                        finding.rule_id == shape.rule && finding.matched_value == token.as_bytes()
                    });
                let on_text = scan_text(&line, &SCANNER, &ALLOWLIST)
                    .iter()
                    .any(|matched| matched.rule_id == shape.rule && matched.range == span);
                let redacted = !redact_text(&line, &SCANNER, &ALLOWLIST).contains(&token);
                if !on_diff || !on_text || !redacted {
                    failures.push(format!(
                        "{} after {escape} in `{context}`: diff={on_diff} text={on_text} \
                         redacted={redacted}",
                        shape.rule
                    ));
                }
            }
        }
    }
    assert!(
        failures.is_empty(),
        "{} escaped context(s) lost:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// a percent escape of url-encoded text and an sgr color sequence of terminal output end in a
/// word byte, so the start boundary admits them explicitly, with a raw or a written escape byte.
const ENCODED_PREDECESSORS: &[&str] = &[
    "token%20",
    "id_token%3D",
    "path%2F",
    "\u{1b}[38;5;186m",
    "\u{1b}[0m",
    "\u{1b}[38:2::255:0:0m",
    "\u{1b}[01;31m\u{1b}[K",
    r"\x1b[1;32m",
    r"\033[0m",
];

#[test]
fn token_after_a_percent_escape_or_sgr_sequence_is_reported() {
    let mut failures = Vec::new();
    for shape in SHAPES {
        let token = shape.token();
        for predecessor in ENCODED_PREDECESSORS {
            let before = format!("{}value={predecessor}", shape.lead);
            let line = format!("{before}{token} end");
            let span: Range<usize> = before.len()..before.len() + token.len();
            let on_diff = scan(&[diff_file(&[line.as_str()])], &SCANNER, &ALLOWLIST)
                .iter()
                .any(|finding| {
                    finding.rule_id == shape.rule && finding.matched_value == token.as_bytes()
                });
            let on_text = scan_text(&line, &SCANNER, &ALLOWLIST)
                .iter()
                .any(|matched| matched.rule_id == shape.rule && matched.range == span);
            let redacted = !redact_text(&line, &SCANNER, &ALLOWLIST).contains(&token);
            if !on_diff || !on_text || !redacted {
                failures.push(format!(
                    "{} after {predecessor:?}: diff={on_diff} text={on_text} redacted={redacted}",
                    shape.rule
                ));
            }
        }
    }
    assert!(
        failures.is_empty(),
        "{} encoded context(s) lost:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn escape_letter_without_its_backslash_still_blocks_the_match() {
    // `n`, `r` and `t` are ordinary word bytes unless a backslash precedes them.
    let mut failures = Vec::new();
    for shape in SHAPES {
        let token = shape.token();
        for glue in ["n", "r", "t", "/n"] {
            let line = format!("{}value={glue}{token} end", shape.lead);
            if reported_rules(&line).iter().any(|rule| rule == shape.rule) {
                failures.push(format!("{} after {glue:?}", shape.rule));
            }
        }
    }
    assert!(
        failures.is_empty(),
        "prefix matched after an escape letter:\n{}",
        failures.join("\n")
    );
}

#[test]
fn escape_like_letter_in_a_base64_run_without_backslash_is_not_reported() {
    // `x`, `u`, `U` and an octal digit open one of the new escape alternatives; glued to a
    // base64 run with no preceding backslash they are ordinary word bytes and must not let the
    // token through, the same false-positive shape the pem reproducers guard against.
    let mut failures = Vec::new();
    for shape in SHAPES {
        let token = shape.token();
        let unbounded = shape.unbounded();
        for glue in ['x', 'u', 'U', '7'] {
            let mut generator = Generator::for_rule(shape.rule, u64::from(glue as u32));
            let mut left = generator.run(B64, 40);
            left.pop();
            left.push(glue);
            let line = format!("{}{left}{token}", shape.lead);
            assert!(
                unbounded.is_match(line.as_bytes()),
                "{}: the unbounded rule does not match after {glue:?}",
                shape.rule
            );
            if reported_rules(&line).iter().any(|rule| rule == shape.rule) {
                failures.push(format!("{} after {glue:?}", shape.rule));
            }
        }
    }
    assert!(
        failures.is_empty(),
        "prefix matched after an escape-like letter with no backslash:\n{}",
        failures.join("\n")
    );
}

#[test]
fn prefix_tokens_in_real_contexts_are_reported_whole() {
    let mut failures = Vec::new();
    for shape in SHAPES {
        let token = shape.token();
        for context in CONTEXTS {
            let line = format!("{}{}", shape.lead, context.replacen("{}", &token, 1));
            let start = shape.lead.len()
                + context
                    .find("{}")
                    .expect("a context carries a token placeholder");
            let span: Range<usize> = start..start + token.len();
            let on_diff = scan(&[diff_file(&[line.as_str()])], &SCANNER, &ALLOWLIST)
                .iter()
                .any(|finding| {
                    finding.rule_id == shape.rule && finding.matched_value == token.as_bytes()
                });
            let on_text = scan_text(&line, &SCANNER, &ALLOWLIST)
                .iter()
                .any(|matched| matched.rule_id == shape.rule && matched.range == span);
            if !on_diff || !on_text {
                failures.push(format!(
                    "{} in `{context}`: diff={on_diff} text={on_text}",
                    shape.rule
                ));
            }
        }
    }
    assert!(
        failures.is_empty(),
        "{} real context(s) lost:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn bounded_token_ending_in_a_dash_is_reported() {
    // a body may end in a byte that is not a word byte; the token is still reported whole.
    let token = format!(
        "AIza{}-",
        Generator::for_rule("gcp-api-key", 0xda54).run(ALNUM, 34)
    );
    for line in [format!("key=\"{token}\""), format!("key={token}")] {
        let matches = scan_text(&line, &SCANNER, &ALLOWLIST);
        assert!(
            matches
                .iter()
                .any(|matched| matched.rule_id == "gcp-api-key"
                    && line[matched.range.clone()] == token),
            "gcp-api-key ending in a dash was not reported whole"
        );
    }
}

/// whether `rule` reports exactly `token` inside `line` on the diff and on the text surface.
fn reported_whole(rule: &str, line: &str, token: &str) -> (bool, bool) {
    let start = line.find(token).expect("the line carries the token");
    let on_diff = scan(&[diff_file(&[line])], &SCANNER, &ALLOWLIST)
        .iter()
        .any(|finding| finding.rule_id == rule && finding.matched_value == token.as_bytes());
    let on_text = scan_text(line, &SCANNER, &ALLOWLIST)
        .iter()
        .any(|matched| matched.rule_id == rule && matched.range == (start..start + token.len()));
    (on_diff, on_text)
}

#[test]
fn age_secret_key_body_is_upper_case_bech32() {
    // age encodes the key as bech32 under the upper-case hrp `AGE-SECRET-KEY-` and prints it
    // upper-case; bech32 never mixes case, so the body is upper-case too.
    let mut generator = Generator::for_rule("age-secret-key", 0xa9e);
    // 26 generated symbols, then every symbol of the alphabet so each one is exercised
    let mut body = generator.run(BECH32_UPPER, 26).into_bytes();
    body.extend_from_slice(BECH32_UPPER);
    assert_eq!(body.len(), 58);
    let with_body = |body: &[u8]| {
        format!(
            "AGE-SECRET-KEY-1{}",
            String::from_utf8(body.to_vec()).expect("ascii body")
        )
    };
    let key = with_body(&body);
    for line in [
        key.clone(),
        format!("SOPS_AGE_KEY={key}"),
        format!("identity: \"{key}\""),
    ] {
        assert_eq!(
            reported_whole("age-secret-key", &line, &key),
            (true, true),
            "age-secret-key not reported whole"
        );
    }
    // a lower-case body under the upper-case hrp is mixed-case, which bech32 rejects;
    // `1`, `B`, `I` and `O` are outside the bech32 alphabet.
    let mut invalid = vec![with_body(&body.to_ascii_lowercase())];
    for outsider in *b"1BIO" {
        let mut changed = body.clone();
        changed[29] = outsider;
        invalid.push(with_body(&changed));
    }
    for (index, value) in invalid.iter().enumerate() {
        assert!(
            !reported_rules(&format!("key={value}"))
                .iter()
                .any(|rule| rule == "age-secret-key"),
            "invalid age key #{index} was reported"
        );
    }
}

#[test]
fn openai_project_key_with_dash_and_underscore_is_reported_whole() {
    // current project keys carry a url-safe base64 body of about 156 bytes around the
    // `T3BlbkFJ` marker; a dash or underscore must not end the match early.
    let mut generator = Generator::for_rule("openai-api-key", 0x0a1);
    let body = format!(
        "{}-{}_{}T3BlbkFJ{}",
        generator.run(ALNUM, 5),
        generator.run(URLSAFE, 5),
        generator.run(URLSAFE, 64),
        generator.run(URLSAFE, 72)
    );
    assert_eq!(body.len(), 164 - "sk-proj-".len());
    let key = format!("sk-proj-{body}");
    for line in [
        format!("OPENAI_API_KEY={key}"),
        format!("client = OpenAI(api_key=\"{key}\")"),
        format!("{{\"openai\":{{\"key\":\"{key}\"}}}}"),
    ] {
        assert_eq!(
            reported_whole("openai-api-key", &line, &key),
            (true, true),
            "openai-api-key not reported whole"
        );
    }
}

/// the pkcs#8 envelope of an rsa-2048 key up to the modulus: sequence, version, rsaEncryption
/// algorithm identifier, octet string, then the inner sequence with its version 0 and the modulus
/// integer header. its bytes `02 01 00 02 82` encode to `AgEAAoIB`, so every such key carries
/// `EAA` inside a base64 run at a fixed column of its first body line.
const PKCS8_RSA_ENVELOPE: &[u8] = &[
    0x30, 0x82, 0x04, 0xbd, 0x02, 0x01, 0x00, 0x30, 0x0d, 0x06, 0x09, 0x2a, 0x86, 0x48, 0x86, 0xf7,
    0x0d, 0x01, 0x01, 0x01, 0x05, 0x00, 0x04, 0x82, 0x04, 0xa7, 0x30, 0x82, 0x04, 0xa3, 0x02, 0x01,
    0x00, 0x02, 0x82, 0x01, 0x01, 0x00,
];

#[test]
fn pkcs8_rsa_body_does_not_report_a_facebook_token() {
    let facebook = SHAPES
        .iter()
        .find(|shape| shape.rule == "facebook-access-token")
        .expect("facebook shape");
    let mut der = PKCS8_RSA_ENVELOPE.to_vec();
    der.extend(Generator::for_rule(facebook.rule, 0x5130).bytes(1152));
    let encoded = base64(&der);
    assert_eq!(
        &encoded[40..48],
        "AgEAAoIB",
        "the envelope places EAA mid-run"
    );
    // unwrapped, the run after that `EAA` is long enough for the old rule: the reported shape.
    assert_eq!(
        facebook
            .unbounded()
            .find_at(encoded.as_bytes(), 42)
            .map(|matched| matched.start()),
        Some(42),
        "the unbounded rule does not match the envelope's EAA"
    );
    let wrapped: Vec<String> = encoded
        .as_bytes()
        .chunks(64)
        .map(|chunk| String::from_utf8_lossy(chunk).into_owned())
        .collect();
    for text in [encoded.clone(), pem_block(&wrapped)] {
        let rules = reported_rules(&text);
        assert!(
            !rules.iter().any(|rule| rule == facebook.rule),
            "facebook-access-token reported on a pkcs#8 body: {rules:?}"
        );
    }
}
